name: Antonio Anguiano
favicon: null
layout_spectrum: 0.40233966265805066
typography_spectrum: 0.24710757471621037
title: Antonio Anguiano - Ecommerce Strategist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f5f7'
    - '#e87d0b'
    - '#522403'
    - '#a44b05'
    - '#78736f'
  brandStrength: 0.33865851955488324
  lightness: 1
  saturation: 0.25542691443115473
  rhythmicContrast: 0.4390202921349555
purpose: []
