name: Antonio Anguiano
favicon: null
layout_spectrum: 0.40233966265805066
typography_spectrum: 0.24710757471621037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.33865851955488324
  lightness: 0.9917521940078586
  saturation: 0.25542691443115473
  rhythmicContrast: 0.4390202921349555
purpose: []
